### ISSUE TITLE
[FEAT] Attributing multiple authors to a single blog post

### ISSUE THREAD

**Issue by gabalafou** [Quansight/Quansight-website#182]

**Comment by bskinn** [comment]
@gabalafou Will LLC and Labs blogs be able to share a single implementation of this, or will the fixes be different?

If the latter, should we perhaps split this issue in two?

**Comment by bskinn** [comment]
During the sprint planning call on 2022-09-19 with @bskinn, @kherma and @tokordys, we preliminarily decided on the following visual layout for the rendering of multiple authors.

----

Each author will have the same "card" as in the current single-author configuration: avatar, Github handle, and name:

![image](https://user-images.githubusercontent.com/11325439/191362695-8e20704b-94d1-4c28-9d27-63a3ae31a852.png)

----

For sufficiently wide layouts (desktop, and perhaps some tablets):

- Authors will be laid out in a grid, with three authors per grid row.
- The overall grid width will vary depending on the length of the names of the authors.
  - In most cases, the author grid will not span the full width of the page text.
- The widths of the grid columns will also vary depending on the widths of the author cards on that post.
  - All columns should have the same width, however
- For rows that do not have three authors, the author cards will fill the grid row starting from the left.

![image](https://user-images.githubusercontent.com/11325439/191366951-a7facb26-9454-47e8-a628-66844da28dc9.png)

**Now that I lay this out**, it looks like rows of *four* author cards **might** work. The catch is in the case of authors with longer names. I don't know if React is smart enough to switch from four-per-row to three-per-row in cases where four-per-row is too wide for the space.

----

For sufficiently narrow layouts (mobile, and perhaps some tablets), author cards will be stacked in a single column, vertically.

While this may leave some conspicuous whitespace on the right hand side of the author card area, due to the variation in length of potential blog author names, it seems more complicated than it's worth to try to juggle a gridded card layout here.

Again, if React is smart enough to be able to switch between a two-per-row and a one-per-row layout depending on the width of the content, that might be a nice way to implement.

![image](https://user-images.githubusercontent.com/11325439/191366799-69d99430-8aeb-4cea-8c21-b40b98f660a4.png)

----

@noatamir / @trallard / @rgommers -- thoughts please w.r.t. Labs
@Katebrack -- thoughts please w.r.t. LLC
@irinafumarel / @MarsBarLee -- thoughts please w.r.t. general design

We are planning to hold off working on this issue until after #396 is completed (conversion of LLC blog to Github/Markdown machinery); so, we have time to iterate on the design decisions here.

Thanks!

**Comment by rgommers** [comment]
That all sounds very reasonable to me, thanks. I'll note that most of our current issues with authors having gone missing is for two-author posts, so if this feature gets complicated due to regridding of many-author posts, you may consider solving the two-author issue first.

**Comment by bskinn** [comment]
@rgommers:

> I'll note that most of our current issues with authors having gone missing is for two-author posts, so if this feature gets complicated due to regridding of many-author posts, you may consider solving the two-author issue first.

Great point. We might even be YAGNI for a design considering more than three authors?

**Comment by bskinn** [comment]
I count zero posts in the LLC archive, and four (out of 56) posts in the Labs archive (based on the Notion board), which have 4+ authors.

**Comment by bskinn** [comment]
There is another visual styling question that must be decided: How to handle multiple authors on the blog gallery pages ([Labs](https://labs.quansight.org/blog) | [LLC](https://quansight.com/library?page=1&type=blog)).

The suggestion from the sprint planning meeting is to only explicitly include the first author on the post. In the case of multiple authors, their authorship will be represented by a "+ # others" annotation in the card for the post.

Regardless of the author count, the post date will be advanced to the next line, left-justified.

----

For example, for Labs (this post might not actually have multiple authors, I just grabbed one ~at random.):

![image](https://user-images.githubusercontent.com/11325439/191568510-1580bb66-083d-4833-9da0-0445be7671ed.png)

And for LLC:

![image](https://user-images.githubusercontent.com/11325439/191569430-4f575264-e692-4abe-bea4-e91d192718be.png)

**Comment by trallard** [comment]
Agree this all sounds reasonable (including the `+2 others` bit) - I think having an implementation that works form more than 2 authors out of the box is ideal (we never know when we might need it)

re

> Each author will have the same "card" as in the current single-author configuration: avatar, Github handle, and name:

The problematic part for me is the GitHub handle - right now it is plain text and not a link so technically useless

It would be best if this were actually a link (with the correct styling) and we could prepend with an `@` or the such

**Comment by bskinn** [comment]
> The problematic part for me is the GitHub handle - right now it is plain text and not a link so technically useless
> 
> It would be best if this were actually a link (with the correct styling) and we could prepend with an @ or the such

Agreed, it should be a link, and more obviously associated with Github. I like your proposal, @trallard.

----

Separately, now that I'm looking closely, I think the vertical alignment of the GH handle and author name vis a vis the headshot also needs to be fixed -- they look like they're placed too low:

![image](https://user-images.githubusercontent.com/11325439/191616832-a9734b07-1fb0-42b3-9d5d-79d8df44e173.png)

**Comment by Surafel-Getachew** [comment]
@bskinn I just want to confirm before starting implementation.
How are we planning to add multiple authors in the `post.md` files
Is it like as categories are added 
`title: 'Why is writing blog posts hard?'
author: [isabela-presedo-floyd, ralf-gommers]
category: [Community, Developer workflows]
`
or comma separated like:
`
title: 'Why is writing blog posts hard?'
author: isabela-presedo-floyd, ralf-gommers
category: [Community, Developer workflows]
`
If we chose to use the first approach array brackets wouldn't it affect the rest of the post.md files

cc @gabalafou

**Comment by bskinn** [comment]
> If we chose to use the first approach array brackets wouldn't it affect the rest of the post.md files

This is something we can discuss with @gabalafou, but yes, my intention would be that it _would_ affect the rest of the posts.

I envision that part of a PR for this would require converting all of the existing post `author` metadata to arrays.

**Comment by irinafumarel** [comment]
Doable. But I haven't seen it implemented yet in the current t blog
https://quansight.com/library?page=1&type=blog



*Irina Fumarel*Graphic Designer

*Quansight* | Your Data Experts
m: +40 734 358 049
w: www.quansight.com  e: ***@***.***
<https://www.linkedin.com/company/quansight>
<https://twitter.com/quansightai>

**Comment by gabalafou** [comment]
I think that in YAML the no-brackets notation, `isabela-presedo-floyd, ralf-gommers`, represents a single string with commas (which we would have to parse/split ourselves later), whereas putting square brackets around it represents an array. 

My hunch is that it would be better if we match the YAML syntax as closely as possible to the structure of the data, meaning we should use the square brackets. Unless there is some really compelling argument to the contrary.

**Comment by bskinn** [comment]
> Doable. But I haven't seen it implemented yet in the current t blog https://quansight.com/library?page=1&type=blog

Correct, @irinafumarel, this hasn't been implemented yet for _either_ Jamstack site.

We're going to be implementing it for Labs on Jamstack. This will be a separate discussion/activity from anything we might do for Consulting on Wordpress. I know we want to have multiple authors on the Consulting blog posts, if we can, but it's not something that has to be implemented by this weekend.

**Comment by bskinn** [comment]
With the merge of #746 and the creation of #797 to mark the need for this feature in the event that Consulting site returns to Jamstack, this issue can be closed.
