### ISSUE TITLE
[BUG] - Links under Consulting in site footer span two lines

### ISSUE THREAD

**Issue by gabalafou** [Quansight/Quansight-website#184]
### What site is this for?

Quansight LLC

### Expected behavior

Each item/link under Consulting in the footer should fit on a single line.

### Actual behavior

Several items/links under Consulting column in the footer are broken across two lines.

### How to Reproduce the problem?

You can see the problem at https://quansight-consulting.vercel.app/

### Anything else?

Here's a screenshot showing the issue. Look at the Consulting column. There are 7 items (consulting services), but 9 lines.

<img width="1331" alt="" src="https://user-images.githubusercontent.com/317883/173084022-89dfa865-ea48-47c4-af54-23c5a517f17e.png">

As a numbered list it would be:

1. [Data Engineering & MLOps](https://quansight-consulting.vercel.app/services)
2. [Infrastructure, Scaling, & Acceleration](https://quansight-consulting.vercel.app/services)
3. [Visualization & Dashboards](https://quansight-consulting.vercel.app/services)
4. [Open Source Integration](https://quansight-consulting.vercel.app/services)
5. [Algorithms, AI, & Machine Learning](https://quansight-consulting.vercel.app/services)
6. [Packaging & Environment Management](https://quansight-consulting.vercel.app/)
7. [Jupyter Technologies](https://quansight-consulting.vercel.app/)

**Comment by bskinn** [comment]
From my perspective, [BUG] on the tracker here no longer means "something Naturaily is to fix", but instead "here is a problem that we might want/need to fix." If this is not the case, then we should develop a finer vocabulary for [XYZ] flags.

One option would be to add bullets to these links. At least then it would be clear where each link starts. (We would probably then also have to add bullets to the leftmost footer links, for visual consistency.)

**Comment by gabalafou** [comment]
> Is this genuinely a bug?

I will leave semantics to you :)

I labeled it a bug simply because this is something that eventually _has to be fixed_.

So in my mind: bug = needs fixing.

But you can label it however you like :)

**Comment by trallard** [comment]
Hmm for reference I never mentioned who should be fixing this. Maybe @gabalafou is more used to my proclivity to dive into semantics. 

To me this sounds more like an enhancement since it technically works but might not be the best or optimal solution. I'll leave it to you @gabalafou as you're the owner

**Comment by gabalafou** [comment]
Well... to be honest, I think it looks terrible. Haha. So then I'll keep the bug label? 

However, to be clear, bug does not equal blocker in my mind. Like, if push comes to shove, I think we **could** (debatably) launch with this bug not fixed. 

But it is a bug in my mind because the footer links should look good (be one line each) no matter what window width you're at. 

But I also see your point of view—as in, it's not "broken" in a functional sense. People can still click on the links. But I'd say it's broken from a visual design perspective.

**Comment by gabalafou** [comment]
This might be easy to fix. We might just do like the microsoft.com site and reduce the font slightly? If that doesn't violate accessibility criteria ...

**Comment by trallard** [comment]
Sure that sounds good

**Comment by bskinn** [comment]
One option that I thought of would be to pull the social media links into the Say Hello column. This would give more horizontal room. This is challenging from a technical Storyblok perspective because of how the components are set up: Footer Social Media as a component is currently implemented to only be able to be its own column, and I don't see any way to add icons-with-links to the Footer Contact component.

Of course, dropping from four columns to three may harm attractiveness of the mobile layout: on mobile, the four footer columns are rendered in two rows...so if we reduced to three columns total, the second row of columns on mobile would only have one column in it.  It still might look ok, though.

Regardless, any of these solutions will require appreciable front-end dev work -- I agree that this is not blocking for launch.

**Comment by trallard** [comment]
@gabalafou  created a label for you and your sanity 😉  ☝🏽

**Comment by bskinn** [comment]
One option is closing up the line spacing within each services area name.

**Comment by bskinn** [comment]
Please disregard, @tokordys, this was meant to be `owner: Quansight`.
