### ISSUE TITLE
[DISCUSS] - Desired formatting/placement of staff titles, especially leadership, on About Us

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#203]
### What site is this for?

Quansight LLC

### Actual behavior

There is currently no dedicated mechanism to place the titles of leadership or other staff onto the About Us page. It is possible to dual-use the 'Project' functionality, meant to add references to the projects that staff are working on, and use it also to include staff titles:

![image](https://user-images.githubusercontent.com/11325439/173434816-f07fc22b-117d-4da4-b93b-978d749b5bf3.png)

The primary purpose of this issue is to discuss whether we want different visual design on these titles.

Should be considered in tandem with #204.

**Comment by gabalafou** [comment]
Where is that image from? Figma?

**Comment by bskinn** [comment]
Storyblok

**Comment by gabalafou** [comment]
Is this about the order in which they appear? I'm not sure I understand what this issue is about.

If it's about order, I would bet that the manual order given to the members under the team folder in Storyblok will propagate to the team leadership component.

In fact, I notice that the order appearing in the Storyblok preview now is different from the screenshot pasted in this issue's description, so I'm wondering if this issue is actually already solved. 

If it is, could you close it @bskinn?

**Comment by bskinn** [comment]
The ordering problem @noatamir already solved.

This is about visual design and placement of the text of the individuals' titles (CEO, CTO, etc.) itself.

Right now we're just reusing/repurposing the 'projects' functionality, meant for the Staff Spotlight entries, for these titles, which is not ideal.
