### ISSUE TITLE
[FEAT] - Add Components to Storyblok providing basic design elements

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#212]
### What site is this for?

Quansight LLC

### Actual behavior

In order to allow Storyblok to reflect Irina's design vision, we would like to add to Storyblok the ability to include individual design elements on pages, in addition to the tailored Components currently available. The goal would be to reproduce all of the elements available on Elementor, including but not limited to:

- Rich formatting on all text fields, including the ability to add links on selected pieces of text within the text fields
- Inserting images inline with text, with controls for image vertical alignment relative to the flow of the text
- Insert centered headers freely
- Insert images freely
- Ability to add hyperlinks to any image

The exact feature set desired will require discussion among the team, as part of a broader plan for if/how to move forward on this.

**Comment by gabalafou** [comment]
Will definitely need discussion. I could be wrong but from a very cursory glance at Elementor, I have a hunch that this may be somewhat at odds with the architectural decisions that went into the website redesign. It may be the case that Storyblok doesn't give that degree of freedom to content authors by design. I think it tries to add more separation between the content team and the web tech team because, as anyone who has spent anytime working on Wordpress knows, it's very easy to bring a site to a slow crawl if you're not fairly judicious about what you add where.
