### ISSUE TITLE
[FEAT] - Allow uploading different hero images for different screens (desktop/tablet/phone)

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#213]
### What site is this for?

Quansight LLC & Labs

### Actual behavior

It is unclear how we will be able to achieve the desired appearance of the hero images across the website as it is currently implemented, where only a single hero image can be uploaded for each page.

To the best of our knowledge, standard practice is to support upload of three hero images for each page, one each for desktop, tablet and mobile views.

Barring detailed guidance on how to achieve the desired design effect with the current Storyblok configuration, we will need this feature added prior to launch.

**Comment by gabalafou** [comment]
I might be misunderstanding this issue. Are you thinking about uploading images with different aspect ratios or different resolutions? Because I think that for different resolutions (for different screen widths), this is already taken care of by the platform. 

You can test it out. First narrow your browser window. Then go to [any page](https://quansight-consulting.vercel.app/library/blog/a-year-in-review-quansight-s-contributions-to-pytorch-in-2021) on the website. Then open Chrome Dev Tools, go to the network panel, clear the accumulated requests, then widen the window while keeping an eye on the network panel. You should notice that the page requests larger image versions as the window gets wider.

**Comment by gabalafou** [comment]
Is this Naturaily or Quansight? I have some thoughts. 

As far as I can tell, the ability to upload images with different aspect ratios was never discussed with Naturaily, nor covered explicitly in [the Figma designs](https://www.figma.com/file/vyWM9qXdXCSAPlTfUjuqrL/Quansight-2021-Website?node-id=1181%3A340) or [the requirements doc](https://docs.google.com/document/d/196XZSMPNzT6-J3DtbI_uHG66-cBk9grh5e0u6_LDt1k/edit).

That said, the mobile screenshots currently do not match the mobile wireframes in Figma, so that part is on Naturaily. I'm not 100% sure but I think all it requires is changing some CSS rules. The Figma files for LLC are not explicit about whether the hero images change dimension on desktop vs mobile, or if they are just "framed" differently.

My understanding is that Irina recently created a set of illustrations for **Labs** that have different dimensions depending on device (desktop vs mobile). However, those were missing from Figma for the past three+ months of development. 

If we absolutely want different aspect ratios for more fine-grained control over how these images get zoomed and/or cropped on portrait versus landscape orientations, then this will require more discussion.
