### ISSUE TITLE
Style inline code segments better

### ISSUE THREAD

**Issue by gabalafou** [Quansight/Quansight-website#318]
Currently in a Labs blog post md(x) file, whenever we have markdown syntax with back-ticks (for inline code), like the following...
 
```text
The syntax `a * b` is used to multiply a and b.
```

...it is rendered to HTML in ways that I would like corrected:

- [ ] There should be no back-ticks in the HTML output
- [ ] <del>There should be background color like GitHub</del> (see conversation below)
- [ ] It should have normal font weight, not bold
- [ ] It should use our custom monospace font (not the system default) 
 
Here is a URL where you can verify these bad stylings: https://quansight-labs-published-h9vlhh1x8-quansight.vercel.app/blog/portable-python-env

**Comment by trallard** [comment]
While reviewing the style for this I did notice that there is a `before` and `after` directive with the ` ` ` character so this needs to be removed entirely

**Comment by bskinn** [comment]
@trallard and/or @gabalafou -- Just finished the initial planning meeting with @kherma and @tokordys.

In order to guide the work on this ticket, they've requested a visual sample of the desired code inline code formatting. I believe the main thing that would benefit from a visual example is the background color -- primarily, which background color should be used -- but an example showing all of the needed changes would be even better.

Could one of you supply this visual example here?  Thanks!

**Comment by trallard** [comment]
Will get this for you tomorrow

**Comment by trallard** [comment]
@gabalafou - you'd originally mentioned as requirement

> Transparent background color (should have some background color like GitHub)

though I have recently come to question whether having a border and/or background colour is the best styling approach 

For example: recently in Nebari we got rid of the background colour + border ([see an example in our docs](https://www.nebari.dev/how-tos/kbatch-howto))

![Submit_batch_jobs_with_kbatch___Nebari](https://user-images.githubusercontent.com/23552331/191599837-2a9369db-1c55-4b06-9c38-d8b0134b52ca.png)

And instead - we have opted for
1. Change the font colour instead of adding a background
2. Ensure the font size matches that of the body font
3. Since we removed the bg + border then the text can be `bottom aligned` with the rest of the text

Compared to the standard approach:


From [docusaurus documentation](https://docusaurus.io/docs/api/docusaurus-config):

![docusaurus_config_js___Docusaurus](https://user-images.githubusercontent.com/23552331/191600132-d527a7f7-f78c-4f9b-ae3c-8cb5d0b8f116.png)

From [Gastby documentation](https://www.gatsbyjs.com/docs/quick-start/)

![Quick_Start___Gatsby](https://user-images.githubusercontent.com/23552331/191600368-8d7b3e97-de6e-42d2-a513-b4e4ebb062fc.png)


I prefer how we have styled the Nebari inline code or the Gatsby approach (no border, minimal padding, same font size for pre and body). WDYT?

cc/ @irinafumarel in case she has strong opinions

**Comment by bskinn** [comment]
Here's an approximation of what it would look like in each of the three primary Quansight brand colors:

![image](https://user-images.githubusercontent.com/11325439/191861457-cb28e5f3-fadd-449c-bafe-0bef19fa8a62.png)

![image](https://user-images.githubusercontent.com/11325439/191861548-d8ef8ea4-dc65-490c-92bd-c894c041df97.png)

![image](https://user-images.githubusercontent.com/11325439/191861618-dd5a4712-f5a9-45d9-8edb-0de176e02dd9.png)

The green is ~unreadable; the light purple is borderline; the dark purple seems ok.

This is a variation on the brand green, with a moderate decrease in luminance and a slight decrease in saturation:

![image](https://user-images.githubusercontent.com/11325439/191861945-46f3e987-6404-4c4f-94ab-4fbb0af18f2f.png)

The brand dark purple seems pretty good to me---no idea where it stands w.r.t. formal a11y guidelines, though.

**Comment by gabalafou** [comment]
This question of how to style inline code segments is out of my area of expertise.

As for personal preferences, I don't have a strong one either way.

But here are some questions I would ask:

1. Do GitHub and Gatsby represent predominant conventions? Should we follow the predominant convention? Does following a predominant convention (so long as it's not a bad convention) aid the reader? Does it help them identify/recognize the styled text as a code segment?
2. Does adding another styling dimension, background color, in addition to the two other dimensions, foreground color and font face, help in terms of accessibility? Does taking it away hurt accessibility?

One thing I notice from my own personal experience, is that when there is a different background color, it helps me to pull out the code segments more easily from the rest of the text. Which can be helpful if I'm in a hurry and all I'm trying to do is remind myself of the exact command line argument or code snippet I'm looking for.

**Comment by bskinn** [comment]
@gabalafou:

> One thing I notice from my own personal experience is that when there is a different background color, it helps me to pull out all of the various code segments on the page more easily from the rest of the text on the page. 

Agreed, for sure.  However:

> ... and all I'm trying to do is remind myself of the exact command line argument or code snippet I'm looking for.

Is this situation likely to be common when reading a blog post, as we're discussing here? This situation seems more relevant to reading API docs.

**Comment by gabalafou** [comment]
@bskinn that's very good point. I think that what Tania is proposing is a definite improvement over what we have now, so we should just go with that. We can always go back and add additional styling if we think that it's important from an access-centered perspective.

**Comment by bskinn** [comment]
Ok. Barring further discussion, we'll move forward in the sprint with inline code formatting of:

- [ ] No border or background color
- [ ] Font color is the dark purple of the Quansight brand colors: `#613ea3`
- [ ] Font weight is normal
- [ ] Font face is the custom Quansight monospace font, not system default
- [ ] Font size is matched to surrounding text
- [ ] Text baseline is aligned with baseline of surrounding normal text.
- [ ] The backticks currently rendering around the inline code need to be removed ([from the `before` and `after` directives](https://github.com/Quansight/Quansight-website/issues/318#issuecomment-1206150954)).


Sample showing the *color* to be used. (The font weight to be used is **normal**, not the bold of this image.)

![image](https://user-images.githubusercontent.com/11325439/193116998-9d7c65bd-82a8-4c5d-8283-458b9b0cfcd5.png)

**Comment by trallard** [comment]
Sounds good. Thanks for sorting this @bskinn

**Comment by kherma** [comment]
@bskinn @gabalafou @trallard One question before opening PR, what is "custom Quansight monospace font" ? Because in styles I see only: Mukta and Inter.

**Comment by gabalafou** [comment]
I meant: use the monospace variant of Mukta (or Inter) if it exists :)
