### ISSUE TITLE
[DESIGN] the social icons "slip out" of the grid

### ISSUE THREAD

**Issue by noatamir** [Quansight/Quansight-website#332]
### What site is this for?

Quansight Labs

### Expected behavior

They should stay in the grid?! @irinafumarel probably has a better answer for this.

### Actual behavior

On desktop the linkedin icon, last on the row of the social icons in the footer, slips out of the grip to varying extent, depending on the window sitze.
<img width="366" alt="Screenshot 2022-07-07 at 15 07 16" src="https://user-images.githubusercontent.com/6564007/177781268-99545d54-891a-4e67-96b8-938dbec72e8b.png">

### How to Reproduce the problem?

go to labs site on desktop, scroll down to the footer, resize the window a bit and notice the linkedin icon position compared to the lower line.

**Comment by kherma** [comment]
@noatamir  Okay, I got it... soo my proposition is to to decrease the gap between footer columns and if, while shrinking the viewport, icons gonna overflow the container, they will simply go to the next line, that way we can prevent it from happening in the future in case of adding more elements. If this is okay for you, the fix is ready. Or we can le
ave the gaps as they are and just wrap icons to the next line... that way on LLC (as there are 4 icons ) they for now will be in row and on Labs ( as there are 5 icons ) they will be wrapper on screens > ~1280px
<img width="1774" alt="reduced-gap" src="https://user-images.githubusercontent.com/63641476/177799412-22e08edf-a033-49b1-a85c-3c33f031ea6f.png">
![shrink-viewport](https://user-images.githubusercontent.com/63641476/177799426-28cf283b-1159-4917-82d8-106bf96c1c74.png)

**Comment by noatamir** [comment]
LGTM @kherma, thanks for the quick fix!
