### ISSUE TITLE
BUG - Broken staff member's display

### ISSUE THREAD

**Issue by trallard** [Quansight/Quansight-website#470]
Right now in https://quansight.com/about-us the Leadership team looks like this:
![About_Quansight___Quansight](https://user-images.githubusercontent.com/23552331/192010852-909e7cab-b104-4f97-a10b-0a106c0c8a27.png)

The only person with a GitHub icon (+link) is Ralf which looks pretty terrible. This has to be removed from the Leadership profiles.

Second - We now have a mixture of folks with projects listed under the GitHub icon and some others without. Which is expected because not everyone work on OSS projects. This also looks pretty inconsistent so I'd suggest removing this altogether to enable consistency. Like in the original Figma design, else everything is going to remain pretty inconsistent. 

![About_Quansight___Quansight](https://user-images.githubusercontent.com/23552331/192011004-93db06cb-3f2f-4c27-8dab-a5f6e0ff1ecd.png)

**Comment by bskinn** [comment]
Removing all of the project names for LLC About Us will be a straightforward Storyblok content change, I will proceed to implement. :+1:

----
----

On the other hand, after looking into it for a bit, I think removal of the Github logos is going to require code and Storyblok schema changes, when considered in combination with this [feature request from #182](https://github.com/Quansight/Quansight-website/issues/182#issuecomment-1254187413):

> It would be best if [the Github username in each author's card] were actually a link (with the correct styling) and we could prepend with an `@` or the such



This is due to an intersection of reasons:

1. A team member's Github handle and profile URL are defined in one place: in their `team` entry on Storyblok.
2. If a team member's profile URL is defined, as currently implemented the `TeamMember` component will *always* render the Github logo/link when building the parent `Team` component.
3. The `Team` component used to render the headshots on the [LLC About Us](https://quansight.com/about-us) and [Labs Team](https://labs.quansight.org/team) pages is common between the two sites ([located in `/libs/shared`](https://github.com/Quansight/Quansight-website/tree/develop/libs/shared/ui-components/src/Team)).
    - Therefore, we can't just disable the Github logo rendering in a piece of LLC-specific code -- the solution has to work correctly on both LLC and Labs sites at the same time.
4. In order to implement the feature requested in #182, each team member will need to have their Github username and profile URL defined in their `team` entry.

(2) and (4) represent the core of the intractable problem for the LLC site. If we define the username and profile for the user, it will cause the Github logo/link to render undesirably on the About Us page. If we do not define the username and profile for the user, it will prevent rendering of the author card as per #182.

---

I think the most robust and workable solution would be to add a boolean `withGithub` flag to the `Team` component, the value of which would be passed to each `TeamMember` component, which indicates whether to render the Github logo and link. A matching Storyblok schema change would expose this flag as a checkbox in the `Team` component, allowing the LLC and Labs sites to respectively disable and enable Github logo/link rendering.

Another possible solution would be to modify the `TeamMember` component such that it detects whether it's being rendered on the LLC or Labs site, and suppresses insertion of the Github logo and profile link when it's rendering for the LLC site. I don't know how to implement such a check, however. (It will not work to check the domain of the page during rendering for `quansight.com` or `labs.quansight.org` or similar, because any check I can imagine will not work correctly on Vercel preview builds, which live at `xyz123.vercel.app` domains.) It also seems like a worse idea because it is less flexible in the long term.

WDYT, @trallard?
