### ISSUE TITLE
[DESIGN] - Reconsider size/layout of hero images

### ISSUE THREAD

**Issue by bskinn** [Quansight/Quansight-website#700]
### What site is this for?

Quansight Consulting

### Actual behavior

The current hero design on many pages for many screen sizes requires visitors to scroll down quite far before getting to the main content. We may want to reconsider this design decision and adjust.

**Comment by asmeurer** [comment]
I'm curious why this was closed. Although https://github.com/Quansight/Quansight-website/issues/449 seems like the same issue. 

I think the hero images should be reduced significantly. Actually I would just remove them entirely. Right now, the entire top part of the page is just an image. You can't even see the title of the post. This is a very bad experience. Here's what https://labs.quansight.org/blog/sympy-documentation looks like 

<img width="1573" alt="image" src="https://github.com/Quansight/Quansight-website/assets/71486/26c21a78-88bb-4bdc-bd78-5b8524943f9c">

Using the web inspector, I deleted the hero image, and it looks like this

<img width="1573" alt="image" src="https://github.com/Quansight/Quansight-website/assets/71486/3f9ef27c-465d-43d0-80b9-1f76e111a3f2">

This is much better because you can immediately see the content (the whole point of the blog). 

Furthermore, the hero images on most posts are the same stock image. They don't add anything of value.

**Comment by asmeurer** [comment]
In UX terms, the current layout has a [false bottom](https://cxl.com/blog/false-bottom/).

**Comment by bskinn** [comment]
@asmeurer This was closed (technically, put into deep freeze) because it's specific to the Consulting Jamstack blog.

This about Labs blog matters should go elsewhere. If it's relevant to #449, please put it there. Else, open a new issue. Thanks!

**Comment by bskinn** [comment]
I'd say this is separate from #449. Different proposal, seems to me, if you end up wanting to argue to remove the heroes entirely.

**Comment by asmeurer** [comment]
If it were my blog, I would just remove the heroes entirely. But I get that may not be tenable. There are ways to show a hero without these issues. For example, look at how Anaconda's blog shows the hero alongside the title (and you can see part of the post above the fold) https://www.anaconda.com/blog/diving-deeper-into-stock-data-analysis-with-python-in-excel
<img width="1630" alt="image" src="https://github.com/Quansight/Quansight-website/assets/71486/8652bcb4-4881-4119-8f81-674b52efa9b6">

Or the conda blog which puts the hero below the title (and again, leaves enough room to see some of the text to avoid the false bottom issue) https://conda.org/blog/2023-11-06-conda-23-10-0-release

<img width="1630" alt="image" src="https://github.com/Quansight/Quansight-website/assets/71486/78c27394-690e-4549-bf62-6e5b4e9245a8">

I imagine the best solution for us will depend on the technical specifics of the site generator we are using.

**Comment by bskinn** [comment]
It's custom React and Tailwind, we can do what we like. 🙂
