### ISSUE TITLE
[MAINT] blurry hero on SciPy array API post

### ISSUE THREAD

**Issue by lucascolley** [Quansight/Quansight-website#786]
The hero of https://labs.quansight.org/blog/scipy-array-api is a little blurry. It looks fine on a big screen but it's quite noticeable on mobile.

It's not a big deal and it may just be that my illustration is the bottleneck, in which case feel free to close this issue :)

If it seems like this could be fixed, here is the original illustration: https://docs.google.com/drawings/d/1VyH4Wep7JN2tfkdzobOSnVXseWlZ7MlP3j3SE-zrvyA/edit?usp=drivesdk. The quality seems to drastically reduce when exporting as png, but I don't know whether I'm just missing a setting or there's something to do with sizes.

Could we try uploading an svg? I've seen that the guidance says to use a png or jpeg, but some other blog posts have been merged with an svg.

**Comment by bskinn** [comment]
@lucascolley, your post is already up! https://labs.quansight.org/blog/scipy-array-api

Getting it posted quickly was more important than refining the image.

However: yes, it should be fine to use an SVG for the hero image. (Note, we can't use SVGs for the _gallery card_ image, though—the one that shows on https://labs.quansight.org/blog—because those images also get used for social previews, and at least one of them (Twitter, IIRC?) doesn't process SVGs.)

So, yes! Please do open a PR to swap the hero image out for the SVG version. I think it should work fine.
