### ISSUE TITLE
[BUG] Issues in Labs Annual Report 2023

### ISSUE THREAD

**Issue by pavithraes** [Quansight/Quansight-website#834]
We have soft published our 2023 Labs Annual Report:

- [Announcement blog post with a nice infographic](https://labs.quansight.org/blog/labs-annual-report-2023)
- [Full report (PDF)](https://labs.quansight.org/annual-reports/quansight-labs-annual-report-2023.pdf)

This issue is to collect any problems in the report/blog before we share these broadly with our community. :)

**Comment by pavithraes** [comment]
The labels in the "Hours spent in OSS projects" plot need to be updated. The top-most bar is for 2023 and lowest one is for 2021. 

- this is done, updates will be live with the next release.

**Comment by guilhermeleobas** [comment]
Skimmed through the PDF and saw some issues there:

* Page 32: uses a black check mark, but page 33 uses a green one? Should the report stick with a single color? Same thing on pages 12/13 and 14.

* Page 23, 35 and 36: White bars on both graphs:

<img width="669" alt="image" src="https://github.com/Quansight/Quansight-website/assets/2712115/e58a576b-ff32-42bb-8fd2-6ab0f97f494a">

<img width="1264" alt="image" src="https://github.com/Quansight/Quansight-website/assets/2712115/b5568d26-aad7-4986-9b87-c3f475daff49">

<img width="630" alt="image" src="https://github.com/Quansight/Quansight-website/assets/2712115/2d62e990-91de-424d-8a9e-fe8c942ba353">

**Comment by trallard** [comment]
@guilhermeleobas the change in bullets colour is fine it is just stylistic shuzz.

Re the plots did you check the current version in https://labs.quansight.org/annual-reports/quansight-labs-annual-report-2023.pdf 

There should not be missing columns and I just reviewed this pdf again and that is not present. So you might have somehow accessed an outdated version?

**Comment by jaimergp** [comment]
Reviewed on 2024-03-04:

* Page 2: 
  * Multiple Array/ Tensor Library support. The slash is not evenly spaced. Either "Array/Tensor" or "Array / Tensor".
  * Capitalization of titles? Some capitalize "And", some don't. There might be other inconsistencies that need adressing.
* [Em-dash vs en-dash](https://www.grammarly.com/blog/dash/). I've seen the en-dash (shorter) used as a colon in many places, but it should be an em-dash (longer). Some examples include page 3 (second and fourth paragraphs) and page 6 (first sentence). In general I'd recommend looking for all the dashes in the report and replacing when appropriate.
* Page 9: `conda` is a NF-sponsored project we have contributed to, so I guess the logo could be here too, but we have conda-forge already. It's mentioned in page 10 too.
* Page 10: The period after stdlib.js, Nebari and conda-store is part of the hyperlink, and should not be. In conda-store, there's even a space after the dot being linked.
* Page 11: 
  * I think this was mentioned, but the years in Hours spent in OSS Project are not correctly assigned.
  * Should it be Hours spent in OSS Projects? Plural.
  * The font size for Hours spent per funding source is larger than in the left-side plot.
* Page 12:
  * Review whether the period after a hyperlink needs to be linked. My opinion is that it should not be linked.
  * The conda 23.10 hyper link is a bit too long. It could stop at the comma.
  * conda-forge is always lowercase. Choose between "Conda-forge" and "conda-forge", but never "Conda-Forge".
* Page 13: A couple of instances of em-dashes needed, as well as periods-included in hyperlinks.
* Page 17: 
  * em-dash in seconda paragraph. 
  * Second checkbox, the link includes an unneeded space.
  * Third checkbox is missing the end period.
  * For some reason, in "Improved JupyterLab's compliance..." I cannot click the hyperlink on "increased" but it does work on "color contrast". Might be Chrome PDF view being buggy, but double check.
* Page 18: review periods-included-in-link.
* Page 19: 
  * You say "Array API Standard" (capitalized) but then "dataframe API Standard" (not capitalized). Intentional or oversight?
  * "Draft dataframe standard" link includes an unneeded space.
* Page 20: "Conda-Store" in the header, but "conda-store" in the text. Is this correct?
* Page 21: em-dash required for "whether user experience (UX)..." and other sentences in the page.
* Page 22: I think Lysandros regularly contributes to PyData events in Berlin (in addition to PyCon DE).
* Page 25, third paragraph: "Lab's members" should be "Labs' members".
* Page 27: "Lucas' experience" link is longer than it should.
* Pages 29, 30: em-dashhhh :) 
* Page 31: The list items do not have an end period, but almost all other list items in the report do. Double check if intentional.
* Page 32: 
  * The ckeckbox for "Pypackaging-native" is misaligned.
  * The conda ecosystem: conda is always lowercase.
  * Line spacing in the menuinst, conda-forge-website and conda-store items is reduced.
* Page 33: there's a double space after "people with disabilities," and "accessibility testing,"
* Page 34: 
  * Here we are capitalizing "Dataframe API" :) 
  * We are writing a 4-digit number as "4,200 hours", but in previous cases we didn't use the command (would have been "4200 hours"). Review. 
* Page 35: 
  * em-dash!
  * Why capitalize "Net income"?
  * Community work orders hyperlink includes an unneeded space
* Page 36: 
  * "tools,
training, mentorship and support they need to join" is missing the Oxford comma after mentorship.
  * Should "nevertheless, we remained committed..." start its own sentence? Or at least a semicolon.
* Page 38:
  * "In June" starts its sentence with an unneeded leading space.
  * Em-dash for the PyPie raffle.
* Page 39:
  * em-dash!
  * "We expect modest growth" needs a space after the period.
  * I was expecting some kind of signature after "Here is to a successful coming year" from the co-directors :)
* Page 40:
  * Check double spaces after "Tania Allard" and "Pavithra Eswaramoorthy" commas.
  * My last name has a dash: "Rodríguez-Guerra".

**Comment by pavithraes** [comment]
@guilhermeleobas - We can't seem to find the white bars in the plots you've highlighted. Which PDF reader do you use? I wonder if it's something tool-specific. :/

**Comment by pmeier** [comment]
I see the same issues with the blank bars as reported in https://github.com/Quansight/Quansight-website/issues/834#issuecomment-1973741564

For example, page 23:

![image](https://github.com/Quansight/Quansight-website/assets/6849766/e1b4f8e3-934c-4fe7-8c18-e2a3b60eeddb)

I just (March 4th, 12:05 UTC+0) took that screenshot on the version currently hosted at https://labs.quansight.org/annual-reports/quansight-labs-annual-report-2023.pdf.

**Comment by pavithraes** [comment]
Thanks, @guilhermeleobas and @pmeier - We can reproduce the blank/white plots when using Firefox to view the PDF file.

**Comment by lysnikolaou** [comment]
- Page 2
   - How Far We’ve Come And Looking Ahead: it's the only one where there's no space between the title and the dots
   - How Labs Internship Works: Should it be "How *the* Labs Internship works"?
   - Can we link to the corresponding page from the respective item? It makes navigating much easier.
- Page 7: Melissa's quote overflowed into mine (at the end of it).  Also, I think it'd be better to change SciPy to NumPy for me.
- Page 8: I'm not in the Labs team and Mateusz is there twice.
- Page 10: As part of our missing 👉 As part of our mission?
- Page 12
   - "The CPython team released Python 3.12" sounds like we worked on the release itself as well. Maybe "The CPython team worked on better and more flexible f-strings (PEP 701) for the Python 3.12 release."?
   - Comma after Accessible pygments: "Accessible pygments, a collection of accessible themes"
- Page 14: "The Jupyter Accessibility team presented workshops and conference talks, and conducted semi-weekly calls" (pluralize call)
- Page 35: First sentence after graphs: "through their" is part of the link in the conda-store hyperlink, but not in the openblas one. 
- Page 36: Inconsistent spacing between first and second paragraph.
- Page 38: “Camp Quansight Island Edition," - comma should probably be outside of quotes

Two general comments:
- Is there a logic in colorizing checklist items differently? Some are green-ish and some are purple-ish, but it's not immediately clear whether there's any semantic differences between the two.
- There's mixing of present participles (-ing), past tense (-ed) and base form for verbs in some checklists (example: page 16). Would it make sense to make this more consistent within individual lists wherever possible?
- I know that the content on the blogpost is mostly pictures, but is there any way we can include real hyperlinks for our social media pages?
